version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  # NEW: PostgreSQL Service
  postgres:
    image: postgres:15-alpine # A lightweight PostgreSQL 15 image
    ports:
      - "5432:5432" # Default PostgreSQL port
    environment:
      - POSTGRES_DB=crypto_db # Your database name
      - POSTGRES_USER=admin # Your database user
      - POSTGRES_PASSWORD=mysecretpassword # CHANGE THIS to a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - API_URL=https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer # This Dockerfile will be updated next
    environment:
      - KAFKA_BROKER=kafka:9092
      - PG_HOST=postgres # Use the service name
      - PG_DATABASE=crypto_db
      - PG_USER=admin
      - PG_PASSWORD=mysecretpassword # CHANGE THIS - MUST MATCH postgres service
    depends_on:
      - kafka
      - postgres # Consumer now depends on postgres

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  postgres_data: # NEW volume for PostgreSQL
    driver: local
  sqlserver_data: # Remove this volume if you're permanently switching
    driver: local