# streaming_data_app/Dockerfile.consumer
FROM python:3.11-slim-bullseye

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer.py .

CMD ["python", "consumer.py"]