version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1 # Unique ID for this node
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT # Define security protocol for CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      
    depends_on:
      - zookeeper

  # NEW: PostgreSQL Service
  # postgres:
  #   image: postgres:15-alpine # A lightweight PostgreSQL 15 image
  #   ports:
  #     - "5432:5432" # Default PostgreSQL port
  #   environment:
  #     - POSTGRES_DB=crypto_db # Your database name
  #     - POSTGRES_USER=admin # Your database user
  #     - POSTGRES_PASSWORD=mysecretpassword # CHANGE THIS to a strong password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data # Persist data



  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - API_URL=https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd
    depends_on:
      - kafka
    command: ["/bin/bash", "-c", "sleep 10 && python producer.py"] # This will now start producer.py automatically

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer # This Dockerfile will be updated next
    environment:
      - KAFKA_BROKER=kafka:9092
      - SQL_SERVER=host.docker.internal # Point to your local machine
      - SQL_PORT=50000
      - SQL_DATABASE=Kafka # Your local DB name
      - SQL_USERNAME=Kafka  # Your local SQL Server username
      - SQL_PASSWORD=Kafka2025  # CHANGE THIS!
    depends_on:
      - kafka
      # - postgres # Consumer now depends on postgres
    command: ["/bin/bash", "-c", "sleep 20 && python consumer.py"] # This will now start consumer.py automatically

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

#volumes:
#   postgres_data: # NEW volume for PostgreSQL
#     driver: local
# #   